version: "2.1"
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "1990:1990"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile" # root caddyfile
      - "./caddy/config:/conf" # caddy configs
      - "./caddy/logs:/logs" # logs
      - "./caddy/certificates:/certs" # certs
      - "caddy_data:/data"
      - "caddy_config:/config"
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ./data/config/jackett:/config
      - ./data/deluge/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/config/radarr:/config
      - ./data/library/movies:/movies #optional
      - ./data/deluge/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/config/sonarr:/config
      - ./data/library/tv:/tv #optional
      - ./data/deluge/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ./data/config/deluge:/config
      - ./data/deluge/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/config/jellyfin:/config
      - ./data/library:/data
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/config/bazarr:/config
      - ./data/library/movies:/movies #optional
      - ./data/library/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Amsterdam
    ports:
      - 5055:5055
    volumes:
      - ./data/config/jellyseerr:/app/config
    restart: unless-stopped
volumes:
  caddy_data:
  caddy_config:
